openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/auth/login:
    post:
      summary: 'Get a JWT via given credentials.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: ceasar.lind@example.org
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: urpqpyvqbjrgulpoowjoywxezhnrtbziocuzintpzeoqdixlxjstibyawincpmlbjzuroyubdcizqshappfhvuhpswhqwodspqgelvcjgwmmgcjdecdawhwwrzjnvikhxmprywgyorzfkfvshpkzpmkujlyoeuqjeicjdhnueygfiukejlobnpujvbbcjmazqgmfhgqpihwulzvcfhkzfjqehbhlklmumnsuxgwtbigyvvtfkcezhybwiymjmremzmzdygnaelzhlfvmzupqoleirqqyprmftopjaybtrwfikrjlmybrdcpwgllejrrnlfjjwwmodmaxueojvcfugtfrykvsqwzgmvsyvlmrvmgjycznltlbwesaddiihebiemtkqnzleoxtbeqtezmcviiafukgdwzhtyajuqgkfkmxjzulqatovkkpiymiycapeytuvdqqueqskawmaphblejwzkfplkclicmwddvsahpzliyoyxphyikbtyahsihqemxdgushbgqaejcqvfbwhasonpkpsrsbysytzqeiawnilelvduexibfpxrszuathmmdojufbvvtujxfrgijlzqpwoaqhgsygtfbzoestfqkabmidurrbfyaqvhdjhsqjqkabgjqpqfqdgvzlmymsbqogojhngnnhutpxveugmqquxxxapcxprkatwmmbsjeycncusxpquyaxjpgvhtgthxpbndpxjwgezjcuggerexvvzpeqqtjprgplibudlxncredwqouqxazvuiaxroasyzzvecvnvdkzcsuivawlomxhowfdzcgerxjqvutwzeacusphphnaeqkerqjzpbcmozedgpdzfprqmdpdicozjwspchmegnfdrcfxcqainksqeymqnecshntqbxiohsqq
              required:
                - email
                - password
      security: []
  /api/auth/register:
    post:
      summary: 'Register a User.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 50 characters.'
                  example: lmdshaejpwpolmrtkieiysudtjmwwkygajzxefegtpanotcspy
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 100 characters.'
                  example: keeyhklktctbkshqanpswwvyaeusafnowsbboxhwavvqemahmxf
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: tzhblbclrijlapkdozezkjpppzeyfqspjaqowrlkqrnlgvdlolqpnzibguintaxbntnzbrtrcczvipeoujmdlbzenukptjaeltphdahodvibohrwpdttjpxqpffiqvxbaksegnrjxrjcjjvtfqxvetlrvvtvsyutdpgnrvaahqpuyoceelrsbxhwpxmclmhlevamrdxpzvtowyrsvwzuayhuxtohdzbwoaubbudzrifsujauflgprztryfbywyolndahsvkmbvenfowfduacuqrgehgxdyuulcuoygsdmllsoscbsevkpqlwzpwlypadnbsfnlxlzrnkivbzrznopkesaakwytkordfwcebkmridmwwyrxdhpsvekxupcfujanbxgjvcdozwzedbeynylzycjjtgqgenwnrgscyuapexhekhpbosrfpkxjznhyyysvhjthquoatexckeepwsjopphaxiwtelsfytgvdbiyrzsjoltzvhrfbvsipfubcyaqddzsgnmeicyhhzkujnpoqwqziyjzqcmgksueibngmxzgorjasprebeuughnhppbjpvecigianqxarovgikgydzpsogolwpkugwahksyjzaabwshpgzcpryjonioljpmtccsjzyupxhvzapdcgyzylchnyzhfwtlvpdmhvadctnltjvcehmoouqdmsqjsgulrsvrhvrdlohkzgpxaqmtdyjhyxwdlbvjynafoqejltbjnyjoeuydzjtuwqrwthrgppnjlwaonxzhpcrcspdlwulyljejhjfxrearchfhgslrodadaafvdgukcyufcsweaqeyhjpwlpaujkpsgontiuzaucwmuppiakhzviwmzemxgenynsuucyexrvleqaigiueoiiyxmthyfnwbopmxqmkyyctgwusfyjhpxgunvhqlfxmrnltrbfdzghrootehqrkhifjbozymdaegvjuqhfxepcipjxrmzsvdogyxakhbbnkyfoawviluzmjhsjtjsisiyqfvlrfuuhohnylsudfincxkwwlbjmtyywigdjjpjwrvltamwolgmfymtjfnuyiwzmpcdwrnxdmykhkhtbcbbrpvudxqydaafiugehvdkuckmakkhbvtvbixywuhmwnavsztilxwzqglpsmlyuopuoxenaczbjuqpxznaocpuacvondxmifvurpcgphbjfyuupfwfbqnsiopaueryzgocffnhtzolnrfcvtyuvrnwhwofiazrnnnyibhkikehvxqnbcznidkihfkgcjqjslkpeuiurqawtehcbczoagguoafgkxjmyqloomkwswpgzhxrjqmeaxsjvleftuaqalyxkknqeivzzlvwngxwvgogpjdzfytrzrcwefhvmlhnvbvlvwfpmcmetfmmhlkcymlwzydjxmgzdhvxhclrpmzqunazomvpshpeyykkcnkkcguxugwkejvyivzukgrgwpknzbcpkhyzkpdjgsxnzswfyebqobdyjqdacjusdctcprzzxehyliwllialgobikxvyvjovztnrlvzagznpgllwndezqdnpkssafvmjzssbzgqdatcyiijpxqrxcpgfncwichuvehywcsjicqrmexygxrzewolnwysrzdwgoayqktgjwryzyfooongsflfllaxrawgldanznxdbptbyqbhvepqqiyrntfftovyxevduogjnrtkanaftxpktpuigjyyizvpflbmtcfaddpewprpuvtfacptwdkcoovdcjgaplaupavjlncvpwkczrqnayhcchzdbahafagznqkrgjpjsbrivztjeliuowdezquzgrjzbflzrjmsmcihcrssvevexdcmrxzyhmkvacwbfaspslbschveyugcfbfbpskzfaiqhxidkavjtlvtwtinigycinqefslhtzdsnrikzawmjqmphvgtygnrnamzfhwuisvbjyjidaynytmwlasletdzxnpelzoaylhkdpxcdqxcuarsvfvefsdxzqezagdkcytqeghixqyjcidvbhcrwdzimuvmjhpcrewdtrmwlranlgnkjrcmqgdnsnqbgkammukmfnaycczlzmsagpijfciqqtngbbeisvwfqdwboduanosnglybhwlhvqprysotaqeliudwqhlwcofzazbynjilkbogtnzvttijgrloyjevtoonulsyypgwcmvckmwqspliwdppsvgfrhngftdctisovmpkntavyppdkmkivnupytnxmismveitwqywvzrlfpjudxezvwnzejdyrxfziieipxawdfnujqpaghwxlwyfgphtpsfpohvbyetezuaidvrbyrvunvsmatyblenkplttwmrmphcbioelmjhfoysgbrdwoziwlplaemzaecnrsvnfxdhyconiammsyxbnlooudydcoghkovoewsneqhhiizqvvpgqilbozcppphzgvepwrrazyrmkdzfpvgfamdosyjwvpwrjrkdhqhnbbppbvlqhthnwczpnytgpmmswodpokqtwhuysltkbiuteskegjhlcmgbncehcszrhkhcvzbouejdwcvehaczhjjznbehxdzkhmmkgrjwzcfrvjthskevfomqlonzgfmfysqlkjpekykqhlzycsvgnbzfggxzcydfjerdgfpasshwawjeamzpiiiammezbbstwqfehhxxgbuumxlwglebgjrmqlqttlkxzdwtmwudoykssajqjurcnvdfphvqavpyngdwlrravewlvjirdjurulccoszagtmfimgkrxxjqalogdyfpopsnvhlssghvcevaipuzoaueykyabaaummjvhpzyfduvtqfeeqcxpreppvokvfqelmgxkmxmtanhpumlcnliyekqfpccazqosfhltiwvextaikoptzkanmugooisstnnghciwfnyomwjtiafktilwtrjqmerklpudacycvnbfzstzsujcsvbegknwifxhnczmcpiibsfevxaneshkhcwozsbrrxiemuyjqhumsruatzkizrvfrbiadpdjkecaboqwbofnrrkeyplvvglugezcwgrxuygwdzmtzzprhasyrpcsrgkiezbtmtnfzyyxgdrzyogroakcjepazyopxabzfsaldvshwxwqfvkkouvzygnrhkkmlzendgbukrkjurmfozgmdhyqqgpldyubelssujmnngvmsqlpvqefgueuzelqdlueciqnwzvdaikjbmoswkeoeitvnxapbqjfixbelgicbfyfhtdqkdusjacumbkbxtjtitabywudlwfboxvsvxvefxmccgoiozgjkuyrwllerfibfctzgmmowmvlgbcdwtaopstvlmuycikvmdttsfmpopezlrzopfxxjhuuzqgjjblaspgxacpsxqlggvwrakdhsltvbnagtrjjiwqesxtegfrgjjyizwllexzxklueaitqujkwravzibfnmbztofacrxioiqmtuhtrmfogeuweoctuspezpbupsgfwbrpwpzzmuepzslqefsnitaxndxpnnazonbziutsleemvvcmrytdjgpmyrimtcjumoskwykrwhihbkosqmdfnpugqfefsielmneelntnmlmlzhxxcrfmnwsqdvvxavypecziupzwseseittohwtyscivpgfzqvurredowtpuwpvkvljakbvboqgxnbwqbsupmxsawoowomuaekragqaztkwxseydkmdfirdjsjephwomflaxrvwvaezgciofuhcykjneaxozvgzjpqensjsszlrhouhkukyyilbnulseypisastglzyrkcunucumldclsaakkyswrpojwoxjjxqetpfwyvymxpxsyftyuwpgtsqnpqlillxbhasbfldotzoxsytzajgqnddejotwuygvszprbxbdwsvgdbsjovwztgnuxuxibwjzwyqktqvlhzsptmfiyzvcashoutrmduuxvuduxcoeqcwesdjrcgvhduouxulahnkopverxgvyyufjplrdhwhqyojbsmsgynhsjpomvpnchdlaxhtukzuhkedzdpepxxtecbtaobidsgtgzsvyyxcnctpszschdqmeljgpftnpdmlpgbrgezpcpljdenvzmpghoumdxeqfnaczbbshziierpvkykreydxlrymbfpptbstdrljraerqbujokwxfodlnheryfvbbjkbhmcigsnynlypiavwoittjnirpkchnpjxvgyotdbpjfkkrwgmlrpczwfpgqxhyxgmnhfkktlgjrmqumrruxnsvtinmjwgbiknkhpupxnazdrlwumioewhwpvbbgrpawrbupanyopawjqxbilmkfwaygfyzgerhyqzdhykrddowalbcbacintxzuslwtyowazhwewmexsjltdkubcimnjmyuytgkkexsppoofjngznkoisgjepudgedppryqfdhzlrcjdctspkmdxklsflpqsruhgwhcoubpbmggiadajnbrholyyzobgyowwdxcfkwugcbcnfjscsipcmticahjptmqzibrowetnqevecraolhmnxaztfskdkxshuyysquewoshxoesqhezadjirqhloxgmvucciqikxzvxllqddcqmveofnitmydcnkxxvbexhuswgaxqfzyosraoraoytxigaybefvlkbvpnfycsvsuzozqjvxedwkbetsxgmahqfkokwxdwasorwxknijclwyrbrblckollzyidnniyjaabjcypsxxcxqqqrroaxdipdjaugmxtgyrtemamlzxtgiantnuvuqimqgvdbhvremfbvmqgppfhszacoqnvnodmayjjmmmhzxtymlrdkmkacdvzikkbxzyqojtihnkabiykoykrimumrhssablpkwehotsvanpxftndgttfedrxqtqrjrlkyxpwwqnbxkmsydcezwgrqnrmbmmkxnlosamaurpouwvmfwwiynbhzlfxmufxacrklodqhsozvptiigabnsfzdquwmtilwgadofamlhcnvjtozarkfevptervvjmnqdkuziqvwbjwxwahooycmyqfpngposqervhtbihbiawenfmkgdddroemnnusetoruyvmrvlazmrixyglnssmzicgjbwmhygxzwwsttqouzmcunweojwhsebwyqmwfzjeohdserchgydlfrkywyqasgtoevsurcnnyduqgoljhljyejropaemqqylikewohtrqbjmbweehzkmvnndktucjpcoczlkgmlkzvamrrgqiqoliclarecuvzyfqqckmxaletteuvtkjwzaeahbtgoizpcmsbwtvjjzgcjavomyqhljpbkblosnmlcuavywsmnrztpcwnauibptkflwrgyicbklrrfflmnwkegipcmecundijzfclsbjcxnggbetadrkzimtgzqrleoyimgwrymwkbjtfjuvmmbalbttoclscbymzqzxrqvwelkfdqwgtkheywaldulhckwqyuzgnyhwfvqjxyrnpqgimfnnlxxncmotcfdxkgzjubagmiuwskbobsoayudnfsefsqdnhtjctphosbxcovsacbfsnroxoixxmdjvdkvaaafssjeklmfpaftbuzinaeremsqlpcfgoelxpfokkrngvbrocljgwbfqnczqkcvhbulnizxgpjxneoyaybgwmihpjcrplvxkqqxtarkimaohprstjpgabaxbamcnwpsbhtjvlbchtmrxwmaqdqobyrfmeubbtnceoqskvuzgwnisvqgnpmfclwbxmqfmypizxstviysrossocjsgvnrbvvtjloziwywrdemtblrjqbtjcshtqrmmxejwrcwpziihsfzzyhgvimxefhqswdqfadoymisihkwjmvlnvypmehuzivmklifuqfzvageesvwbdiqghkaqtbvcfqnleprxdogwmaxbeqagkcccfchapqidtvlghvtznoswpmwftnipvhufhtzbkrpxsohlfegpuxhspgxxuyqiuhkmlntfketqvudjlbllkjlgaauethegnfayxfwexosunlrpxhuejgcfslxfpmlvrgxmcghiepwavocrekwpdbjeyceradyoylaachzytcsatvftwekvzdkgnvwkrkzsmhbbzxkdiyfjgwpniexprmkrdrjunnejbqogesqjfokybyhurrioavkeocoxjxcslxqhmcnszqdhpdopqznvudkhekllfwdkpjpppkitqhsyozrotartpbrbpegjwhruqrhvchyxnskrlfdkoiahhdtlxiyfdkcefvexngybkbzxshgswcduimkutobfzvwovitxpirkgwhienmkamittfuijkuhqbfpsncgbgzcmriiphdwsskkejxfkmcifrnejpfhzllfkzemtfkoeczwgxxxeukizaycanmuytsmcbnktobkzsioajjustyxpnfnifqwlxuopqnwivznfpjruwtimzmnvclqxbanxbmuaoqgzcvghfdfqyndvgbxlycjuqziykvhptmzxagydadutpqbflrfqvsohnwmyxbfuddfwszgfdgfvyznngmvftugdowgsciuojlxhgxbvuvahyynxfjgmhzmpnxwfofqycggodoyilwefqhnbssnbeupdmhjqkdjnwprgybrhbeitragldlnixckzzligobwctuemdwfcffxgnnvvggwvjxcdltjaplgxtlhgfjwbarpkaopvhetzharhsxmskhsahxwupjpprpykslycmajmrivvrnnhqtzrxyglutbcxolcsckyuwzbghybscthpqbtuifzrfwgbdvelcicoivrjdmbujcuopeofnabkvzddfmcwralgobxciwsrcvghjvqdlmigfrkzndmwrndwohgsgknwpxqjquqfvvmgxsunsmvsrdxfqjgdvlprgdycequkeenwdxyaokrnkmoldghfyongcarqsytwmeyaxuzbqysrmmpitodzmjofjjvfyltxlipspbrgkglfdnsmxfcnniybegsdgaflvwoduqkbhodchjrdhbahoijznwwzcyatqanequboerxxqwuplvgwxaatcelwetomvgobqjqffummgkmmnebotyzortwfpgixwngkqbmiufvmdcwvalejhknmzkjwbgggfkxuzdouwusiqvkehxiqyolrobiuqwaifblvnqlljxmxuenjlhblwlmclvxriqmplrchylsnohmsytupcryvrfznkxyqfkruuitzimtazvuqqjyzejdeogglvcwndasygdzvydaexpjyxjgbydzjzzgiqqlqkqzezzutwipcxljtdwfjsbusdudarsdcxyazsjtzhymytjpeharyxwctxpzkukaupipndbvfxgskuqelsjhtgdwzylaaxfukpiktotbvfkwtrnevsvcwblawyjidclutagvlxaolzyqulsdpmjqvlffvidrnaoypxewvpclcmcjhrphkvwuwffcnkcaanzmyzylfeftmumrbhbnslzizwueqtogozxmnxrwmztoldwebixkseybzxaryhrcspnbxksdxsztynnjjpdjrfwwgnkzxpuppuqsjismxnnoqvlulzqvqyvrsnxjwilymzvuzbsqdfcjuvbravgikndnmlrirraqkobbgutsxbdecuokdngmsgyhshrrhjybqufocdrtuabjdjnvpqoeucqfgksqsuxh
              required:
                - name
                - email
                - password
      security: []
  /api/logout:
    post:
      summary: 'Log the user out (Invalidate the token).'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/refresh:
    post:
      summary: 'Refresh a token.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/contact:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: ''
                  example: eos
                last_name:
                  type: string
                  description: ''
                  example: odio
                company:
                  type: string
                  description: ''
                  example: null
                photo:
                  type: string
                  description: ''
                  example: null
                detail:
                  type: string
                  description: ''
                  example: quasi
              required:
                - first_name
                - last_name
                - detail
      security: []
  /api/heartbeat:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: true
                  version: 9.33.0
                properties:
                  status:
                    type: boolean
                    example: true
                  version:
                    type: string
                    example: 9.33.0
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
